### PR TITLE
Adding Your Portfolio Website

### PR DESCRIPTION
**Pull request by Bisht13**
Hey Manpreet,
Inspired from Dennis' I have made a portfolio website for you!
Here is how it looks 
pg1
pg2
pg3
pg4
One can also toggle the dark mode and light mode by clicking on the circle below the Personalize themes 
Hope you like it 😄 !

### CODE REVIEW

**Comment by manpreetrathore** [comment]
Could you make it a bit more interesting rather than just copying the template brother. Try making something interesting and pretty. If not i'll accept this as well in the hacktoberfest. Happy coding buddy!

**Comment by Bisht13** [comment]
I am not so much into web dev :sweat_smile: just started out

**Comment by Bisht13** [comment]
@manpreetrathore Thank you for the label
Btw This is a pull request so the good first issue doesn't match here 
Maybe you can make a new issue about editing this website and add the good first issue there

**Comment by manpreetrathore** [comment]
Added it buddy. Its still open to modify. so anytime you feel like. 
Happy coding mate :)

**Comment by divinenaman** [comment]
Hey, I want to give it a shot.
It would be helpful if you mention what sections do you require on your Portfolio like Project Showcase, Contacts etc or I can make it according to my preferences.

**Comment by manpreetrathore** [comment]
> 
> 
> Hey, I want to give it a shot.
> It would be helpful if you mention what sections do you require on your Portfolio like Project Showcase, Contacts etc or I can make it according to my preferences.

It's fine however you do it. Its totally up to you do whatever you want mate XD

**Pull request merged**
